### PR TITLE
Hide the local cnab directory and introduce $BUNDLE_ARG

### LINKED ISSUE #320: Improve abstraction over CNAB
The goal is to improve our abstraction so that as people learn
porter by just using it and seeing what happens, they are more likely to
fall into using it in a way that we recommend.

Some of the day 0 questions/comments that I have already seen and want to address
before they even pop into their heads:

* _Should I first do `porter build` and then edit bundle.json going forward
and run the commands passing in the -f bundle.json arg?_
* _Where should I copy my files into the container?_
* _What is the /cnab/app directory in the container and do I have to use it?_
* _I feel like I need to know the spec first before I can build a bundle_
* _Does porter work with just porter bundles or any CNAB bundle?_

## Bundle Directory Argument

Porter will give them the bundle directory (/cnab/app) as a build arg.

```
FROM ubuntu:latest

# Put your bundle's files here
ARG BUNDLE_DIR

# Your porter.yaml is in BUNDLE_DIR, so you can reference these with a relative path
COPY hi.txt $BUNDLE_DIR/

# You are encouraged you to copy files from their canonical location
ADD https://github.com/ashleymcnamara/gophers/raw/master/WonderWomanGopher.png $BUNDLE_DIR/
```

The `porter create` command will output a template Dockerfile and a README.

## Autocopy Files in Bundle Directory

When the user chooses to not use a template Dockerfile, all of the files in the bundle directory (the directory that contains the porter.yaml file), are automatically copied into the invocation image under /cnab/app.

## Consolidate CNAB files in cnab/

Currently we output the bundle.json to the root of the bundle directory. This
makes it easy for users to think that they should/could be doing something with
it. Since we already have a directory named cnab, we can move it there, and
explain that everything in that directory is part of our compatibility with the
CNAB spec and are generated files.

As part of that change, the cnab directory should move from being created during
`porter create` to `porter build` to reinforce that it is a generated artifact
from the build. This also helps with the question of if people need to check in
the cnab directory because Porter will automatically generate it before each
build.

## Example: Working with bundle files

Currently we hint to users that they can copy files into cnab/ and that's how
they can get files into the invocation image. Now with the Dockerfile template
generated during `porter create`, and cnab/ becoming more ephemeral, here's
what the recommendation looks like:

1. `porter create` to get a Dockerfile and porter.yaml.
1. Files can be put in the root of the bundle directory, or in subdirectories.
1. They are copied into the bundle via COPY commands in the Dockerfile.

    ```
    COPY hi.txt $BUNDLE_DIR/
    ```
1. The manifest can safely reference the files using relative paths (now that we
    are going to stop merging manifests). As always if an advanced bundle
    chooses to place files out of the BUNDLE_DIR, like /var/www, they can
    reference them with absolute paths.

## When to use porter.yaml vs bundle.json

The porter manifest is the source of truth that has an intermediate
representation as bundle.json. The bundle.json file is a critical implementation
detail, but the user shouldn't need to know about it when working with porter
bundles. On the flip side, porter should support working with bundles created
in other tools that only have a bundle.json file.

Currently the cnab action commands (install/upgrade/uninstall) all accept a
`--file` argument which points to a bundle.json file, because the duffle library
operates on the bundle.json. For porter bundles, it's easy to end up installing
an out-of-date bundle.json file because subsequent changes have been made to the
porter.yaml without a `porter build` being run. This is a symptom of our leaky
abstraction over CNAB/duffle.

The `install`, `upgrade` and `uninstall` commands will do the following:

1. Check if the cnab/ directory and bundle.json exist and if not, execute a build.
1. Compare the `custom["sh.porter"]["manifestHash"]` stamp in bundle.json
    of the manifest. If it is out-of-date, execute a build.
1. Execute the install, passing in the up-to-date bundle.json.

Since there are now two scenarios where you can pass in a manifest to
porter's commands, here are the flag conventions:

1. Use `--file` when explicitly specifying a path to a porter.yaml file.
1. Use `--cnab-file` when working with non-porter bundles, and you only
    have a bundle.json file. This will skip porter's manifest logic, and jump
    directly to calling into duffle's libraries.

### LINKED ISSUE #422: [Possible BUG] porter.yaml not copied when dependency exists
hi team,

I'm trying (really) hard to get my first package to work with a dependency.
The dependency is located in ./myBundle/bundles/myDependency/porter.yaml:

image

after a `porter build` here is the result:
image

Am I doing something wrong?

[EDIT] I just tried to move the dependency to `%HOME/.porter/bundles` and I do have the same result
image

SwissPorter 😄

### LINKED ISSUE #426: Remove generated files before build
Before `porter build`, any generated files leftover from a previous `porter build` should be deleted.

Files to delete:
* cnab/
* Dockerfile

### PR DESCRIPTION
**Pull request by carolynvs**
This hides the local cnab directory that porter generates during the
build phase from the user. The goal is to avoid giving the user
expectations about the directory and its contents.

In addition, we now delete and recreate the generated files, .cnab and
Dockerfile, before we do a build to avoid any odd bugs.

I've also tweaked our gitignore to take advantage of the new naming
rules.

Closes #320 
Closes #422 
Closes #426

### CODE REVIEW

File: pkg/build/build.go [hunk 1]
```diff
@@ -0,0 +1,17 @@
+package build
```
Comment (carolynvs) [inline pkg/build/build.go]: I have plans to split out the build logic into this package in another PR. This is in prep for #361.
