### PR TITLE
Fix template not used for help command

### LINKED ISSUE #656: Custom help template not used for published version of porter
## Describe the bug
When I build porter locally, then run `porter help` I see the custom help template. But when I use a published release of porter, I don't.

## To Reproduce
1. Install porter from the https://porter.sh/install
2. Run `porter help`

## Expected Output

```
$ porter help
I am porter 👩🏽‍✈️, the friendly neighborhood CNAB authoring tool

Usage:
  porter [command]

Examples:
  porter create
  porter build
  porter install
  porter uninstall

Resources:
  bundles     Bundle commands
  credentials Credentials commands
  instances   Bundle Instance commands
  mixins      Mixin commands

Aliased Commands:
  archive     Archive a bundle
  build       Build a bundle
  create      Create a bundle
  install     Install a new instance of a bundle
  invoke      Invoke a custom action on a bundle instance
  list        list instances of installed bundles
  publish     Publish a bundle
  show        Show an instance of a bundle
  uninstall   Uninstall a bundle instance
  upgrade     Upgrade a bundle instance

Meta Commands:
  docs        Generate markdown docs
  schema      Print the JSON schema for the Porter manifest
  version     Print the application version
```

## Actual Output
```
$ porter help
I am porter 👩🏽‍✈️, the friendly neighborhood CNAB authoring tool

Usage:
  porter [command]

Examples:
  porter create
  porter build
  porter install
  porter uninstall

Available Commands:
  build       Build a bundle
  bundles     Bundle commands
  create      Create a bundle
  credentials Credentials commands
  docs        Generate markdown docs
  help        Help about any command
  install     Install a new instance of a bundle
  instances   Bundle Instance commands
  invoke      Invoke a custom action on a bundle instance
  list        list instances of installed bundles
  mixins      Mixin commands
  publish     Publish a bundle
  schema      Print the JSON schema for the Porter manifest
  show        Show an instance of a bundle
  uninstall   Uninstall a bundle instance
  upgrade     Upgrade a bundle instance
  version     Print the application version
```

## Version
Copy the output of `porter version` below

porter v0.16.1-beta.1 (f1f5217)

### PR DESCRIPTION
**Pull request by dev-drprasad**
# What does this change
Fix custom templates not used for commands and little refactor

**Ouput of `porter help`:**

```
I am porter 👩🏽‍✈️, the friendly neighborhood CNAB authoring tool

Usage:
  porter [command]

Examples:
  porter create
  porter build
  porter install
  porter uninstall

Resources:
  bundles     Bundle commands
  credentials Credentials commands
  instances   Bundle Instance commands
  mixins      Mixin commands

Aliased Commands:
  archive     Archive a bundle
  build       Build a bundle
  create      Create a bundle
  explain     Explain a bundle
  install     Install a new instance of a bundle
  invoke      Invoke a custom action on a bundle instance
  list        list instances of installed bundles
  publish     Publish a bundle
  show        Show an instance of a bundle
  uninstall   Uninstall a bundle instance
  upgrade     Upgrade a bundle instance

Meta Commands:
  docs        Generate markdown docs
  schema      Print the JSON schema for the Porter manifest
  version     Print the application version

Flags:
      --debug   Enable debug logging
  -h, --help    help for porter

Use "porter [command] --help" for more information about a command.
```
# What issue does it fix
Closes #656 

# Notes for the reviewer
Renamed `helptext` directory to `templates`. It made sense to me

# Checklist
- [ ] Unit Tests
- [ ] Documentation
  - [x] Documentation Not Impacted

### CODE REVIEW

File: cmd/porter/main.go [hunk 1]
```diff
@@ -1,3 +1,5 @@
+//go:generate packr2
```
Comment (carolynvs) [inline cmd/porter/main.go]: This is what was missing and causing things to not work properly for binaries not build on dev machines. Thanks for figuring that out! 👍 

It can be hard to tell because packr will fallback to the filesystem when the data isn't found in the binary. Because this line was missing, nothing was being built into the binary for the help text. But it was working on dev machines because the files were present locally. 😆 

The other changes in the file aren't necessary and should be reverted.

Comment (dev-drprasad) [reply cmd/porter/main.go]: The other changes are intentional.
I thought directory name: `templates`  makes sense than `helptext` because in future we may need to add other templates. So, i refactored that logic

If i am wrong/misunderstood , i can revert if you want

Comment (carolynvs) [reply cmd/porter/main.go]: Our preference for pull requests, is it [limit them to a single task](https://github.com/deislabs/porter/blob/master/CONTRIBUTING.md#how-to-get-your-pull-request-reviewed-fast). In this case the issue is to fix the help text and since the refactoring wasn't necessary for the fix, we prefer to not include it in the same PR.

Later, if we had an issue where we needed to add more templates to cmd/porter, that would be the time to refactor. Right now we don't have anything like that on the backlog though.
