### PR TITLE
Remove internal params in `explain` output

### LINKED ISSUE #1091: internal parameters should not be displayed
## Describe the bug
The porter-debug parameter is printed out during `porter explain`

## To Reproduce

Create a bundle with porter and then run porter explain on it.

## Expected behavior
Any internally generated parameters, porter-* should not be displayed during `porter explain` or `porter inspect`.

## Porter Command and Output
```
$ porter explain
Name: whalegap
Description: An example bundle that demonstrates how to sneak a whale-sized bundle through an airgap
Version: 0.1.0

Credentials:
Name         Description   Required
kubeconfig                 true

Parameters:
Name           Description                                                     Type      Default              Required   Applies To
msg            a message for the whales to speak                               string    whale hello there!   false      All Actions
porter-debug   Print debug information from Porter when executing the bundle   boolean   false                false      All Actions
release        helm release name                                               string    whalegap             false      All Actions
```

## Version
```
$ porter version
porter v0.26.3-beta.1-27-g637c4311 (637c4311)
```

### PR DESCRIPTION
**Pull request by dev-drprasad**
# What does this change
Don't show internal params in output of `explain`

# What issue does it fix
Closes #1091 

[1]: /CONTRIBUTING.md#when-to-open-a-pull-request

# Notes for the reviewer

# Checklist
- [x] Unit Tests
- [x] Documentation (N/A)
- [x] Schema (porter.yaml) (N/A)

### CODE REVIEW

**Comment by dev-drprasad** [comment]
@carolynvs You mentioned, `porter inspect` shows parameter list in issue. But I see `porter inspect` showing only image and invocation image list. So, I added necessary changes to `explain` command only

File: pkg/porter/explain.go [hunk 1]
```diff
@@ -114,6 +114,8 @@ func (s SortPrintableAction) Swap(i, j int) {
 	s[i], s[j] = s[j], s[i]
 }
 
+var porterInternalParams = []string{"porter-debug"}
```
Comment (carolynvs) [inline pkg/porter/explain.go:117]: If we make this a `map[string]struct{}` (optimized for memory) or `map[string]bool` (not optimized but can be easier to understand sometimes), and then checkIsInternalParam can be simplified, where it returns the second return value from querying the map

```golang
var porterInternalParams = map[string]struct{}{
    "porter-debug": struct{}{},
}

// ...

// ok holds if the specified key is present in the map
_, ok := porterInternalParams[inputParam]
return ok
```

File: pkg/porter/explain.go [hunk 2]
```diff
@@ -169,6 +171,17 @@ func (p *Porter) printBundleExplain(o ExplainOpts, pb *PrintableBundle) error {
 	}
 }
 
+func checkIsInternalParam(inputParam string) bool {
```
Comment (carolynvs) [inline pkg/porter/explain.go:174]: suggestion: This would read better in English if we changed the name to `isInternalParam`, for example look at line 219 in generatePrintable, it would become `if isInternalParam(p) {`. 

It's a pattern that can be useful at times, naming a function "isNOUN", or "canVERB",  etc.

**Comment by carolynvs** [comment]
Oh great! At one point inspect was going to do more, and we changed it's scope. I wasn't sure if it was affected or not so thanks for checking.

**Comment by carolynvs** [comment]
I am looking into why the integration tests are failing, it does not appear to be related to your changes.

**Comment by carolynvs** [comment]
Your change is fine, verified manually locally. I believe that this is a problem with how the CI action is merging your change with master. I'm going to merge and then see how it lands on main. If there is a problem, I'll resolve any conflicts.
