### PR TITLE
Extend version command to help troubleshoot porter

### LINKED ISSUE #614: Extend version command to help troubleshoot porter
I want a command to help me troubleshoot when someone submits a bug report. Instead of having to asking questions about "what os are you running", "what mixins are installed?" etc, I'd rather tell them "run this one command and send me the output".

I think we can add a `--system` flag that when present prints additional information about what is installed in the porter home directory.

```console
$ porter version --system
porter v0.14.1-beta.2 (72dd5df)

System
--------
os: darwin
arch: amd64

Mixins
------
Name         Version          Author
aws          v0.1.2-beta.1    DeisLabs
az           v0.2.1-beta.1    DeisLabs
```

The following will need to be changed:
* `cmd/porter/version.go` - add system flag
* `pkg/porter/version.go` - 
  * Add VersionOpts struct to hold what we use currently plus the system bool and have version take this new opts struct instead.
  * Add method to collect additional information when system flag is present (os, arch)
  * Use [porter.ListMixins](https://github.com/deislabs/porter/blob/b24cdd412147c8156942f6d8accb489e71e48e6f/pkg/porter/mixins.go#L42) to get a list of the installed mixins, and use similar table printing as [porter.PrintMixins](https://github.com/deislabs/porter/blob/b24cdd412147c8156942f6d8accb489e71e48e6f/pkg/porter/mixins.go#L26-L30)
  * Make a new struct to contain all the collected information and handle printing it according to the requested output format (json, table, etc).
  * Add tests to version_tests.go

### PR DESCRIPTION
**Pull request by phillipahereza**
# What does this change
Adds `--system` flag to the `version` command to print additional information about what the system on which porter is being run and any installed mixins

```
$ porter version --system
porter v0.14.1-beta.2 (72dd5df)

System
--------
os: darwin
arch: amd64

Mixins
------
Name         Version          Author
aws          v0.1.2-beta.1    DeisLabs
az           v0.2.1-beta.1    DeisLabs
```

# What issue does it fix
Closes #614

# Notes for the reviewer
This is a draft PR to get help

# Checklist
- [x] Unit Tests
- [ ] Documentation
  - [ ] Documentation Not Impacted

### CODE REVIEW

**Comment by phillipahereza** [comment]
@carolynvs am I on the right path

**Comment by carolynvs** [comment]
@phillipahereza Yes, this is what I was looking for. 👍 Once you are ready for a review, just take the PR out of draft, by clicking the button "Ready for Review" or maybe it's called "Request Reviews". 

Then I'll go over it and provide detailed feedback. I just redid our CI pipeline, so I'll kick off a new test run for you right now.

File: pkg/porter/version.go [hunk 1]
```diff
@@ -16,3 +26,55 @@ func (p *Porter) PrintVersion(opts version.Options) error {
...
+
+func (p *Porter) PrintDebugInfo(opts version.Options) error {
+	// force opts to print version as plaintext
+	opts.RawFormat = string(printer.FormatPlaintext)
+	err := p.PrintVersion(opts)
+	if err != nil {
+		return errors.Wrap(err, "Failed to print version")
+	}
+
+	printSectionHeader(p.Context.Out, "System")
```
Comment (dev-drprasad) [inline pkg/porter/version.go]: You can achieve this functionality using go templates. I think it will more readable. Just a opinion

**example:**
```golang
const ts = `
version: {{.Version}}
{{if .Sys -}}

System
--------
os: {{.Sys.OS}}
arch: {{.Sys.Arch}}
{{- end}}
`
v := Version{
	Version: "1.0.0",
	Sys:     nil,
}
tmpl, _ := template.New("system").Parse(ts)
tmpl.Execute(p.Context.Out, v)
```

File: cmd/porter/version.go [hunk 2]
```diff
@@ -7,15 +7,18 @@ import (
 )
 
 func buildVersionCommand(p *porter.Porter) *cobra.Command {
-	opts := version.Options{}
+	opts := version.VersionOpts{}
```
Comment (carolynvs) [inline cmd/porter/version.go]: Would you please move `VersionOpts` into `pkg/porter/version.go`. The `version` package is intended for other mixins to reuse when they implement the version command. 

That will change this line to look like to `opts := porter.VersionOpts{}` but won't otherwise change much. It's just to help with the organization of the code.

File: cmd/porter/version.go [hunk 3]
```diff
@@ -7,15 +7,18 @@ import (
...
 	cmd := &cobra.Command{
 		Use:   "version",
 		Short: "Print the application version",
 		PreRunE: func(cmd *cobra.Command, args []string) error {
-			return opts.Validate()
+			return opts.Options.Validate()
```
Comment (carolynvs) [inline cmd/porter/version.go]: Please simplify the here back to: 

```suggestion
			return opts.Validate()
```

We can do that because `Options` is embedded in `VersionOpts` (it isn't a named field) so functions available on that type can be called without having to specify that it's coming from `Options`. Apologies if you knew about that, I'm just sharing Go tips in case they are helpful! 😀

File: cmd/porter/version.go [hunk 4]
```diff
@@ -7,15 +7,18 @@ import (
...
 		},
 		RunE: func(cmd *cobra.Command, args []string) error {
-			return p.PrintVersion(opts)
+			if opts.System {
```
Comment (carolynvs) [inline cmd/porter/version.go]: The convention in Porter is that all logic should be in `pkg/porter`, and `cmd/porter` should just wire up cobra to functions defined in that package. 

Please move the check against `opts.System` into `PrintVersion`, so that the code in this file goes back to looking like:

```go
RunE: func(cmd *cobra.Command, args []string) error {
   return p.PrintVersion(opts)
}
```

If you are curious about why, I did a [talk about how Porter is designed at GopherCon](https://youtu.be/eMz0vni6PAw). The short answer is that it helps us test, and allows for people to build on top of porter's libraries.

File: pkg/porter/version.go [hunk 5]
```diff
@@ -16,3 +26,55 @@ func (p *Porter) PrintVersion(opts version.Options) error {
...
+}
+
+func printSectionHeader(out io.Writer, header string){
+	underline := "-------"
+	_, _ = fmt.Fprintf(out, "\n%s\n%s\n", header, underline)
+
+}
+
+func (p *Porter) PrintDebugInfo(opts version.Options) error {
+	// force opts to print version as plaintext
```
Comment (carolynvs) [inline pkg/porter/version.go]: Apologies for not catching this when I first checked the PR, but this new `--system` flag needs to work in conjunction with the `--output plaintext|json` flag. So `PrintDebugInfo` needs to support printing to json as well.

File: pkg/porter/version_test.go [hunk 6]
```diff
@@ -51,3 +54,30 @@ func TestPrintJsonVersion(t *testing.T) {
...
+	pkg.Version = "v1.2.3"
+
+
+	p := NewTestPorter(t)
+
+	opts := version.Options{}
+	p.TestConfig.SetupPorterHome()
+	err := opts.Validate()
+	require.Nil(t, err)
+	err = p.PrintDebugInfo(opts)
```
Comment (carolynvs) [inline pkg/porter/version_test.go]: After you move this method and the check for `opts.System` into `p.PrintVersion`, I recommend updating this unit test, to exercise your if statement as well. So it should create `VersionOptions {System: true}` and pass that to `p.PrintVersion(opts)`.

File: cmd/porter/version.go (hunk 3 above)
Comment (phillipahereza) [reply cmd/porter/version.go]: Thanks, this is all very helpful 🙏🏾

File: pkg/porter/version.go [hunk 7]
```diff
@@ -1,80 +1,111 @@
...
-func (p *Porter) PrintDebugInfo(opts version.Options) error {
-	// force opts to print version as plaintext
+func (p *Porter) PrintDebugInfo(ctx *context.Context, opts VersionOpts, versionMetadata mixin.Metadata) error {
 	opts.RawFormat = string(printer.FormatPlaintext)
-	err := p.PrintVersion(opts)
+	mixins, err := p.ListMixins()
+	sysInfo := getSystemInfo()
 	if err != nil {
-		return errors.Wrap(err, "Failed to print version")
+		_ = errors.Wrap(err, "Failed to get list of mixins")
```
Comment (carolynvs) [inline pkg/porter/version.go]: Instead of ignoring the error (like it's doing now), or returning it (which would make it very hard to use this command for troubleshooting problems 😅 ), we can have it print a debug message and then keep going:

The contributing guide has a section on how to handle debug logging:

https://github.com/deislabs/porter/blob/master/CONTRIBUTING.md#logging

You can check `p.Debug` and then print to `p.Err` following the example in the guide, then have the rest of the command continue. That way even if we can't print any mixin data, at least we are able to print the data we _do_ have.

File: pkg/porter/version.go [hunk 8]
```diff
@@ -1,80 +1,111 @@
...
+os: {{.SysInfo.OS}}
+arch: {{.SysInfo.Arch}}
+{{if .Mixins}}
+Mixins
+-------
+{{.Mixins.PrintMixinsTable}}{{end}}
+`
+		tmpl, err := template.New("systemDebugInfo").Parse(plaintextTmpl)
+		if err != nil {
+			_ = errors.Wrap(err, "Failed to print system debug information")
```
Comment (carolynvs) [inline pkg/porter/version.go]: At this point, if we can't parse the template, then we should return the error, and not ignore it with `_` because it's an unrecoverable error. 

If the template isn't parsed, then continuing on to call Execute on the template (which is nil when err is populated) will cause a nil reference exception.

**Comment by phillipahereza** [comment]
> Thanks for adding this into Porter! It's going to really help out when people submit bug reports. 💯

My pleasure, thanks for guiding me through the whole process
