### PR TITLE
Throw error to user when empty step found in manifest

### LINKED ISSUE #873: Action without mixin specified causes panic
Install the following:

1. 
```
╭─ralph at surfacebook in ~/work/go/src/github.com/squillace using
╰─○ curl https://cdn.porter.sh/latest/install-linux.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1111  100  1111    0     0   1121      0 --:--:-- --:--:-- --:--:--  1121
Installing porter to /home/ralph/.porter
Installed porter v0.22.2-beta.1 (4401e74)
installed exec mixin
exec v0.22.2-beta.1 (4401e74) by Porter Authors
installed kubernetes mixin
kubernetes v0.22.2-beta.1 (4401e74) by Porter Authors
installed helm mixin
helm v0.10.1-beta.1 (83466c2) by Porter Authors
installed azure mixin
azure v0.7.1-beta.1 (a05ef92) by DeisLabs
installed terraform mixin
terraform v0.5.1-beta.1 (597a442) by Porter Authors
installed az mixin
az v0.4.1-beta.1 (c27e188) by Porter Authors
installed aws mixin
aws v0.2.1-beta.1 (e7b6884) by Porter Authors
installed gcloud mixin
gcloud v0.3.1-beta.1 (a8240d4) by Porter Authors
Installation complete.
Add porter to your path by running:
export PATH=$PATH:~/.porter
```

2. Note that the `az` mixin you have used extensively is there, version v0.4.1-beta.1 (c27e188). So, put `- az` in the porter.yaml file:
image

3. Build the bundle:
```
porter build
Copying porter runtime ===> 
Copying mixins ===> 
Copying mixin exec ===> 
Copying mixin kubernetes ===> 
Copying mixin helm3 ===> 
Copying mixin az ===> 

Generating Dockerfile =======>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x83a057]

goroutine 1 [running]:
get.porter.sh/porter/pkg/manifest.(*Step).GetMixinName(0x0, 0xc0000ce4f0, 0x5)
        /home/vsts/work/1/s/gopath/src/get.porter.sh/porter/pkg/manifest/manifest.go:445 +0x37
get.porter.sh/porter/pkg/build.(*DockerfileGenerator).getMixinBuildInput.func1(0x1bdcea2, 0x7, 0xc00037f9b0, 0x5, 0x5)
        /home/vsts/work/1/s/gopath/src/get.porter.sh/porter/pkg/build/dockerfile-generater.go:212 +0xbd
get.porter.sh/porter/pkg/build.(*DockerfileGenerator).getMixinBuildInput(0xc0004fdd18, 0xc0000ce3f8, 0x4, 0x2d406c0, 0x0, 0x4d5b38)
        /home/vsts/work/1/s/gopath/src/get.porter.sh/porter/pkg/build/dockerfile-generater.go:219 +0x12f
get.porter.sh/porter/pkg/build.(*DockerfileGenerator).buildMixinsSection(0xc0004fdd18, 0xc000120000, 0x9, 0x10, 0x0, 0x0)
        /home/vsts/work/1/s/gopath/src/get.porter.sh/porter/pkg/build/dockerfile-generater.go:178 +0x1c3
get.porter.sh/porter/pkg/build.(*DockerfileGenerator).buildDockerfile(0xc0004fdd18, 0x0, 0x0, 0x83b565, 0x22, 0x4f)
        /home/vsts/work/1/s/gopath/src/get.porter.sh/porter/pkg/build/dockerfile-generater.go:61 +0xd4
get.porter.sh/porter/pkg/build.(*DockerfileGenerator).GenerateDockerFile(0xc0004fdd18, 0x0, 0x0)
        /home/vsts/work/1/s/gopath/src/get.porter.sh/porter/pkg/build/dockerfile-generater.go:37 +0x40
get.porter.sh/porter/pkg/porter.(*Porter).Build(0xc00038cc00, 0xc0004fdd00, 0x0, 0x0)
        /home/vsts/work/1/s/gopath/src/get.porter.sh/porter/pkg/porter/build.go:38 +0x155
main.buildBundleBuildCommand.func1(0xc000435400, 0x2d406c0, 0x0, 0x0, 0x0, 0x0)
        /home/vsts/work/1/s/gopath/src/get.porter.sh/porter/cmd/porter/bundle.go:53 +0x35
github.com/spf13/cobra.(*Command).execute(0xc000435400, 0x2d406c0, 0x0, 0x0, 0xc000435400, 0x2d406c0)
        /home/vsts/work/1/s/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002d6780, 0x0, 0x18dc300, 0xc0000ac058)
        /home/vsts/work/1/s/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/vsts/work/1/s/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /home/vsts/work/1/s/gopath/src/get.porter.sh/porter/cmd/porter/main.go:18 +0x27
```

### PR DESCRIPTION
**Pull request by dev-drprasad**
# What does this change
Throw error to user when empty step found in manifest

# What issue does it fix
Closes #873 
Related #532 

# Notes for the reviewer

sample output of `porter build`
```console
3 errors occurred:
	* validation of action "install" failed: found an empty step
	* validation of action "uninstall" failed: found an empty step
	* validation of action "status" failed: found an empty step
```

# Checklist
- [x] Unit Tests
- [x] Documentation
  - [x] Documentation Not Impacted

### CODE REVIEW

**Comment by carolynvs** [comment]
Yes, it does prevent the panic from occurring during build. However it doesn't help the person know about the problem and fix the porter.yaml which is the intent behind the other issue you referenced #532.

There may also be a problem ( I haven't tested this ) where it avoids the panic during build, allows you to create the bundle with the syntax error, but we may still need to then avoid errors caused by the syntax error when the bundle is then executing during a porter install.

A different fix for this that I would prefer to see is that when you detect this condition during `porter build`, to stop and return an error message to the user that explains the problem that you found and how to fix it. That way we don't let bad syntax end up in the resulting bundle to begin with. 😀 How does that sound?

**Comment by dev-drprasad** [comment]
It makes sense than silently ignoring the error. I made changes as per your suggestion.

File: pkg/manifest/manifest.go [hunk 1]
```diff
@@ -68,15 +70,22 @@ func (m *Manifest) Validate() error {
...
 	if err != nil {
-		result = multierror.Append(result, err)
+		result = multierror.Append(result, errors.Wrapf(err, fmt.Sprintf(invalidStepErrorFormat, "uninstall")))
+	}
+
+	for actionName, steps := range m.CustomActions {
+		err := steps.Validate(m)
+		if err != nil {
+			result = multierror.Append(result, errors.Wrapf(err, fmt.Sprintf(invalidStepErrorFormat, actionName)))
+		}
```
Comment (dev-drprasad) [inline pkg/manifest/manifest.go]: I added validation for custom actions also though its not relevant to issue. I think we forgot to add before

File: pkg/manifest/manifest.go [hunk 2]
```diff
@@ -393,6 +400,9 @@ type Step struct {
 }
 
 func (s *Step) Validate(m *Manifest) error {
+	if s == nil {
+		return errors.New("found an empty step. probably you forgot to mention it")
+	}
```
Comment (dev-drprasad) [inline pkg/manifest/manifest.go]: To Reviewer: I thought this is right place to check for `nil`. Let me know your opinion

**Comment by dev-drprasad** [comment]
Ready for Review

File: pkg/manifest/manifest.go [hunk 3]
```diff
@@ -393,6 +400,9 @@ type Step struct {
 }
 
 func (s *Step) Validate(m *Manifest) error {
+	if s == nil {
+		return errors.New("found an empty step. probably you forgot to mention it")
```
Comment (vdice) [inline pkg/manifest/manifest.go]: I might suggest we just leave the error message as a succinct `found an empty step`.

File: pkg/manifest/manifest.go (hunk 1 above)
Comment (carolynvs) [reply pkg/manifest/manifest.go]: good catch, thanks! 👍

File: pkg/manifest/manifest.go (hunk 3 above)
Comment (carolynvs) [reply pkg/manifest/manifest.go]: Agreed, let's use Vaughn's suggested wording for the error message, I think it is more clear

File: pkg/manifest/manifest.go (hunk 2 above)
Comment (carolynvs) [reply pkg/manifest/manifest.go]: It seems like the natural spot, and it works with your test data, so 👍
